### ISSUE TITLE
背景图片固定的效果挺不错的！

### ISSUE THREAD

**Issue by BruceZhaoR** [movesan/msblog#1]
想学习一下，请问除了把scroll变成了fixed之外，css或者其他地方有需要调整的吗？
另外你的按个二维码生成不错，也准备借鉴一下，以后用到的新博客中去。

**Comment by movesan** [comment]
@BruceZhaoR 
恩只需把改成fixed就可以了，但是会有个图片显示区域的变化，因为fixed是相当于body的，所以我又增大了图片显示区域，使图片尽可能全的展示。另外改成fixed后会有个响应式的问题，页面变窄后背景显示区域有问题，找了好多方法暂时也没有解决。

二维码那个也是借鉴了其他人的，感觉还是很方便的，新博客正在弄吗？弄好了可以去参观一下~
